### ISSUE TITLE
Not connecting to WiFi

### ISSUE THREAD

**Issue by shapingstuff** [interactionresearchstudio/connected-shelf-esp32#1]
I can access the shelf at 192.168.2.1 but it doesn't appear to connect to the WiFi when I press the save button.

The CONNECTED SHELF WiFi persists.

Some feedback as to whether the shelf is connected/disconnected would be useful. I'm not sure if the buttons are working.

I've checked here: http://irs-iot.ddns.net/devices/ and it doesn't appear.

**Comment by michaelshorter** [comment]
I'm having exactly the same issue in Liverpool. I enter my details, press save on both text feilds and nothing happens.

**Comment by andysheen** [comment]
Hi both, 

I think this was more a UX issue. The Camera only works in normal mode when not using the Captive Portal. I've added a Status badge, a reset button and a note on resetting to return to normal mode https://github.com/interactionresearchstudio/connected-shelf-esp32/commit/5e1d7a57c18318fe62c289b8862b168becbf35cb
