### ISSUE TITLE
Device name disapears from the device name box

### ISSUE THREAD

**Issue by shapingstuff** [interactionresearchstudio/connected-shelf-esp32#3]
Can the device name remain in the device name box once connected, or just after pushing save?

It caught me out a little and I did it a second time because it defaulted.

It would be good to see what the current device name is in the box at all times.

**Comment by andysheen** [comment]
This should be the case, i'm not able to reproduce this. I'm the latest code, the device name is updated on start up of the page and that's it. Please try this and see if it's fixed

**Comment by shapingstuff** [comment]
Fixed.
