### ISSUE TITLE
1000x1600 framesize by default

### ISSUE THREAD

**Issue by shapingstuff** [interactionresearchstudio/connected-shelf-esp32#7]
I have been testing the images this morning it will be a million times better if we can get the 1000x1600 settings as a default in the advanced settings and for the recommended settings.

 It would be much better to have the right image size rather than cropping from 1200x1600 because then we don't risk capturing the room on either side while uploading. 720x1080p doesn't look nearly as good. 1000x1600 also works especially well on tablets.

Here in the settings, it would be good to always have the default toggle at 1000x1600 so it is always clear that this returns you to the shelf dimensions.

![Default-frame-size](https://github.com/interactionresearchstudio/connected-shelf-esp32/assets/12648622/9fc7f956-3ad8-4973-9204-cb028b503f09)

This code could maybe be included after initialising the camera as a boolean on the toggle for the default setting (if that works for you):

  // crop the image according to the shelfie dimensions
  sensor_t * s = esp_camera_sensor_get();
  s->set_res_raw(s, 0, 0, 0, 0, 0, 90, 1600, 1000, 1600, 1000, true, true);

Although it doesn't look much it makes a big difference to have the extra space without cropping.

![MicrosoftTeams-image (31)](https://github.com/interactionresearchstudio/connected-shelf-esp32/assets/12648622/5077446d-d9d2-43ba-b1af-238fb7051a31)

1000x1600

![MicrosoftTeams-image (32)](https://github.com/interactionresearchstudio/connected-shelf-esp32/assets/12648622/a647ac31-5383-4670-af5d-7826b2e2af6f)

720x1080

**Comment by shapingstuff** [comment]
It could - I'm not totally against it. However - I've been noticing on the actual saved images we have the sides of people's rooms and that seems like something they might not be aware of and a possible privacy issue. The other option is to crop when uploaded and save the cropped image.

**Comment by andysheen** [comment]
Happy to update if everyone wants this. Just a note, iPads are 4:3, so if we offer this for people to use on their own devices, it's most likely going to be an iPad and we'll have the same issue in reverse :)

**Comment by andysheen** [comment]
I think the cleanest way would be to offer it as a dropdown option with all the framesize names as 16:10 and set this to the default option

**Comment by shapingstuff** [comment]
If it isn't too difficult to include we could always use it as a setting and try it out?

**Comment by shapingstuff** [comment]
> I think the cleanest way would be to offer it as a dropdown option with all the framesize names as 16:10 and set this to the default option

This works. Much cleaner.

**Comment by andysheen** [comment]
https://github.com/interactionresearchstudio/connected-shelf-esp32/actions/runs/7211221733 Should fix https://github.com/interactionresearchstudio/connected-shelf-esp32/issues/7 and https://github.com/interactionresearchstudio/connected-shelf-esp32/issues/8.

**Comment by andysheen** [comment]
<img width="501" alt="Screenshot 2023-12-14 at 15 29 03" src="https://github.com/interactionresearchstudio/connected-shelf-esp32/assets/20442164/4c56dda6-4ee0-4bbc-9a83-70f9cf947453">
